baseURL = 'https://martinsam.github.io/lessources/'
languageCode = 'fr'
title = 'LesSources.bio'
theme = 'ananke'


#disqusShortname = "ananke-demo"
MetaDataFormat = "yaml"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "The last theme you'll ever need. Maybe."
  faceboook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/intro.jpg"
  custom_css = ["custom.css"]
  site_logo = "farmer_white.png"
  favicon = "farmer.png"


defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false

[languages]

  [languages.fr]
    languageName = "Français"
    weight = 1

  [languages.en]
    languageName = "English"
    weight = 2

  [languages.de]
    languageName = "Deutsch"
    weight = 3


# MENU GLOBAL
# Hugo adaptera automatiquement les liens selon la langue active
# grâce à pageRef.

[[menu.main]]
identifier = "news"
name = "Actualités"
pageRef = "/news"
weight = 1

[[menu.main]]
identifier = "shop"
name = "Boutique"
pageRef = "/shop"
weight = 2

[[menu.main]]
identifier = "lodging"
name = "Hébergement"
pageRef = "/lodging"
weight = 3

[[menu.main]]
identifier = "pizza"
name = "Pizza"
pageRef = "/pizza"
weight = 4

[[menu.main]]
identifier = "contact"
name = "Contact"
pageRef = "/contact"
weight = 5